---
abstract: 'Mock a DNS Resolver object for testing'
author:
  - 'Marc Bradshaw <marc@marcbradshaw.net>'
build_requires:
  Test::Exception: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-DNS-Resolver-Mock
requires:
  Net::DNS::Packet: '0'
  Net::DNS::Question: '0'
  Net::DNS::Resolver: '0'
  Net::DNS::ZoneFile: '0'
  base: '0'
  strict: '0'
  warnings: '0'
version: '1.20200215'
x_generated_by_perl: v5.30.1
x_serialization_backend: 'YAML::Tiny version 1.73'
